### PR TITLE
[ADD] l10n_cl_product

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by nelsonramirezs — APPROVED** [review]

**Review by nelsonramirezs — CHANGES_REQUESTED** [review]
This is the best practice but is not mandatory field
http://www.sii.cl/factura_electronica/formato_dte.pdf
Vlrcodigo @max3903

**Review by nelsonramirezs — APPROVED** [review]
LGTM!!!

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Pull request merged**
