### PR TITLE
[ADD] l10n_cl_electronic_invoicing

### PR DESCRIPTION
**Pull request by max3903**
Ping @nelsonramirezs

### CODE REVIEW

**Comment by Danisan** [comment]
Hello. Will you try to clear de ci failure? Or need my interaction?

**Comment by max3903** [comment]
Hello @Danisan I don't have the time to clean up the code now. I set you as a reviewer for your information.

**Comment by celm1990** [comment]
On v13 odoo has chilean localization or is incomplet???


Many code is taken from repo https://gitlab.com/dansanti/l10n_cl_fe because not keep colaborators

**Comment by max3903** [comment]
Hello @celm1990 This is for version 12.

Previous contributors are still listed here:
https://github.com/OCA/l10n-chile/pull/8/files#diff-b739f2b9c58b677caae848bad0af3f0a

**Comment by Danisan** [comment]
> On v13 odoo has chilean localization or is incomplet???
> 
> Many code is taken from repo https://gitlab.com/dansanti/l10n_cl_fe because not keep colaborators

@celm1990 in v13.0 the work in 13 is quite different. I think we should review what we have new in 13 and complement that.

**Comment by Danisan** [comment]
> Hello @Danisan I don't have the time to clean up the code now. I set you as a reviewer for your information.

@max3903 so, this module will stay unmerged until CI goes green. Meanwhile, I will be commenting on some portions of code. I will live it open by now.

**Comment by max3903** [comment]
@Danisan Sounds good. Thank you.

**Comment by max3903** [comment]
@Danisan @nelsonramirezs I reached a point where the module installed. There are still few errors, but it's more manageable. I need your help fixing the rest. Are you available to help?

**Comment by nelsonramirezs** [comment]
> @Danisan @nelsonramirezs I reached a point where the module installed. There are still few errors, but it's more manageable. I need your help fixing the rest. Are you available to help?

@max3903 Yes, Ill be available starting from tomorrow.

**Comment by max3903** [comment]
@nelsonramirezs @rto-odoo Runbot is red due to warnings but you can connect to it and use it.

**Pull request merged**
